### ISSUE TITLE
SDVX 2024060401 asset update failure

### ISSUE THREAD

**Issue by Telain** [22vv0/asphyxia_plugins#1]
Running fork-6.0.3.3 on Asphyxia v1.50c. When trying to run Update Webui assets, it fails here every time. Best I can tell, it's trying to find a folder. Even when I make the manually and make sure permissions are wide open, I get the same error.

Attempted on edgar131/asphyxia docker and windows. Couldn't find the log to get error from Windows.

  [core] error: WebUIEvent Error: copyResourcesFromGame
  [sdvx@asphyxia] error: Error: ENOENT: no such file or directory, mkdir 'plugins/sdvx@asphyxia/webui/asset/arena_rank'
Error: ENOENT: no such file or directory, mkdir 'plugins/sdvx@asphyxia/webui/asset/arena_rank'
    at Object.mkdirSync (node:fs:1349:3)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1639:33)
    at Object.copyResourcesFromGame (/usr/local/share/asphyxia/plugins/sdvx@asphyxia/handlers/webui.ts:574:10)
    at EamusePlugin.CallEvent (/snapshot/build-env/index.js)
    at /snapshot/build-env/index.js
  [unknown] error: Error: ENOENT: no such file or directory, open 'plugins/sdvx@asphyxia/webui/asset/arena_rank/glow.png'

**Comment by Telain** [comment]
I realized edgar131 copies the plugin directory every time, so updates wouldn't be kept between reboots. I made my own docker that just runs whatever files you have on the volume, but the error persists.

**Comment by 22vv0** [comment]
copyResourcesFromGame:574 expects to find the plugins folder in the current process dir (_/usr/local/share_) but there is no plugins directory there. 

In a non-docker environment it is likely that you would have the asphyxia executable at the same folder as the plugins directory so the process dir would be the executable's directory, and would have no trouble looking for plugins folder.

But edgar131/asphyxia runs from _/usr/local/share/bootstrap.sh_ so the current process dir would be _/usr/local/share_ which is NOT where the plugins directory is, it's in _/usr/local/share/asphyxia_.

Workaround is to add 'asphyxia/' to the directory string (in handlers/webui.ts - lines 573, 574 and 659)
![image](https://github.com/22vv0/asphyxia_plugins/assets/10232214/52cb2ba3-dd20-4fb8-8501-a7b6243473a3)

**Comment by Telain** [comment]
Thanks for the info. Adding chdir "/usr/local/share/asphyxia" to bootstrap.sh fixed the issue.
