### ISSUE TITLE
Request: LEAGUE WORLD

### ISSUE THREAD

**Issue by maurioski** [22vv0/asphyxia_plugins#10]
can add in the webui  some option to manipulate the LEAGUE WORLD from  world.ts?

enable/disable, change date start, end,

**Comment by 22vv0** [comment]
i can add a toggle for LEAGUE WORLD. 

not too sure on the date override because it would be tricky to do as there could be a situation where your override date overlaps with future league dates, and would have unintended side effects, like an upcoming league date ending prematurely, etc.

**Comment by maurioski** [comment]
got it.
