### ISSUE TITLE
Add WebUI to ddr world and also add subtracted and added judgements score my a previous song. Fix now loading time only if that issue is related to the ddr plugin.

### ISSUE THREAD

**Issue by makoflagkk** [22vv0/asphyxia_plugins#2]
I would like to see those two features added to the DDR Plugin fork that supports WORLD in a future update.

**Comment by 22vv0** [comment]
hello, i've pushed some updates to score and ghost data loading that enables display of score difference, however this currently unfortunately doesn't allow for existing ghost data to be loaded. more info on the [plugin README](https://github.com/22vv0/asphyxia_plugins/blob/mdx/README.md).

let me know what you think!

**Comment by makoflagkk** [comment]
> hello, i've pushed some updates to score and ghost data that enables display of score difference, however this currently unfortunately doesn't allow for existing ghost data to be loaded. more info about this [here](https://github.com/22vv0/asphyxia_plugins/blob/5ca14ab461a07c4c7f7feb922f7b350e22edcc09/handlers/ddrworld.ts#L22).
> 
> 
> 
> also have yet to start doing some webui stuff.
> 
> 
> 
> let me know what you think!
> 
> 

Sorry for the late reply college sucks, but everything works great at least visually. I don't notice any problems unless I missed something. I had a question how would I create a server private that is official using this website for like DDR X2 - WORLD https://kailua.eagle.ac/oauth/authorize?client_id=EA714EE743F80D06177E08F061D9DB020024DC4B&redirect_uri=https%3A%2F%2Feagle.ac%2Fauth%2Fkailua%2Fcallback&scope=vulkan&response_type=code&state=MSE7M1jsGu4BowrfqsI0nNeRyqmmCZtogsA7qrrO

**Comment by 22vv0** [comment]
I fear that this is out of the scope of this repo, as this is only for use in asphyxia. Creating your own ea server is a huge task but If you want to start making your own, you can do so with a sufficient enough knowledge in programming/coding & RE.

Asphyxia is a great practice to learn how the games communicate with k0nami servers so they get the server-sided features they introduce. So I recommend asphyxia as a starting point, then move up from there. Besides, I don't think there's an asphyxia plugin for older DDR games (that I'm aware of,) you could be the person to make them!
