### ISSUE TITLE
Posible add extracted musicdb and use coursedb

### ISSUE THREAD

**Issue by maurioski** [22vv0/asphyxia_plugins#7]
hello, i  already have unpacked from the last update from -001-2024101500 bt the plugin dont read the file, and get the course if can add in the server to see reflected and unlocked in game?
[coursedb.zip](https://github.com/user-attachments/files/17599875/coursedb.zip)
[musicdb.zip](https://github.com/user-attachments/files/17599876/musicdb.zip)

**Comment by 22vv0** [comment]
make sure you have the musicdb file in the directory I specified in the README, and make sure you got your settings configured here: 
![image](https://github.com/user-attachments/assets/523853f6-b932-4d29-a934-31e2a5169cde)

And DDR World does not have a courses feature (that I know of) as of today.
