### ISSUE TITLE
DDR World Asphyxia Plulgin Last 3 Remaining Notifications Will Keep Popping up Every Game Play

### ISSUE THREAD

**Issue by alrd6228** [22vv0/asphyxia_plugins#9]
These last 3 song notifications keep on existing after every full gameplay loop. 

Not sure how to disable them permanently after initial notification. 

![462546272_425560187032541_4582878763675289000_n](https://github.com/user-attachments/assets/54847834-2ee0-4ca3-a841-5152b6242535)
![462557336_1225908978716836_4915366819993401087_n](https://github.com/user-attachments/assets/8bb55062-f354-4d10-91aa-7cafcaf94363)
![462562503_931180175600992_8056385934709766184_n](https://github.com/user-attachments/assets/2b2ce25f-5e44-4c5e-b6ec-682b89d09674)

**Comment by maurioski** [comment]
same for me, same 3 songs.

**Comment by alrd6228** [comment]
> same for me, same 3 songs.

I've tried looking through the code to see what could possibly be impacting these populating but cannot make sense of it.

**Comment by 22vv0** [comment]
I found out that the 3 event data related to this aren't saving if your game isn't in Gold cab mode. That's why they show up everytime you login (assuming you're not in Gold mode.)

If you have all the songs unlocked by default anyway, you can disable this event by commenting out lines 286 to 288 in data/world.ts, and restarting asphyxia.

**Comment by alrd6228** [comment]
> I found out that the 3 event data related to this aren't saving if your game isn't in Gold cab mode. That's why they show up everytime you login (assuming you're not in Gold mode.)
> 
> If you have all the songs unlocked by default anyway, you can disable this event by commenting out lines 286 to 288 in data/world.ts, and restarting asphyxia.

Confirmed fixed and working. 

For anyone looking specifically for that code, look for this. I already added the "//"

//{id: 110, no: 0, cond: 1, rwrd: 38759, type: 43, comp: 0, save: 1 },
	//{ id: 111, no: 0, cond: 1, rwrd: 38758, type: 43, comp: 0, save: 1 },
	//{ id: 112, no: 0, cond: 1, rwrd: 38756, type: 43, comp: 0, save: 1 }

**Comment by 22vv0** [comment]
> Any idea which code can stop world leage? I'd imagine it's the same and this code in relation maybe.
> 
> export const LEAGUE_WORLD = [ //{ id: 1, name: "第1回 WORLD LEAGUE", name_eng: "The 1st WORLD LEAGUE", start: BigInt(Date.parse('8 Oct 2024 01:00:00 GMT')), end: BigInt(Date.parse('6 Nov 2024 08:00:00 GMT')), summary: BigInt(Date.parse('6 Nov 2024 09:00:00 GMT')), advanceBorder: [0, 0, 0]
> 
> and just comment out.

Comment out line 748 in handlers/ddrworld.ts instead.

**Comment by alrd6228** [comment]
> > Any idea which code can stop world leage? I'd imagine it's the same and this code in relation maybe.
> > export const LEAGUE_WORLD = [ //{ id: 1, name: "第1回 WORLD LEAGUE", name_eng: "The 1st WORLD LEAGUE", start: BigInt(Date.parse('8 Oct 2024 01:00:00 GMT')), end: BigInt(Date.parse('6 Nov 2024 08:00:00 GMT')), summary: BigInt(Date.parse('6 Nov 2024 09:00:00 GMT')), advanceBorder: [0, 0, 0]
> > and just comment out.
> 
> In the mean time, comment out line 748 in handlers/ddrworld.ts instead (EDIT: also line 234 in data/world.ts) I will add a toggle for enabling/disabling world league next time.

Confirmed working. Removed world league notifications. 

I have a separate world plugin that someone else has been working on for some time if you want a copy. Might be useful to compare if you're interested
